# Generated by Django 2.2.3 on 2019-07-16 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('rated', models.CharField(blank=True, max_length=200)),
                ('runtime', models.CharField(blank=True, max_length=200)),
                ('genre', models.CharField(blank=True, max_length=200)),
                ('director', models.CharField(blank=True, max_length=200)),
                ('writer', models.CharField(blank=True, max_length=200)),
                ('actors', models.CharField(blank=True, max_length=200)),
                ('plot', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('awards', models.CharField(blank=True, max_length=200)),
                ('imdb_id', models.CharField(blank=True, max_length=200)),
                ('type', models.CharField(blank=True, max_length=200)),
                ('production', models.CharField(blank=True, max_length=200)),
                ('year', models.SmallIntegerField(blank=True)),
                ('metascore', models.SmallIntegerField(blank=True)),
                ('released', models.DateField(blank=True)),
                ('dvd', models.DateField(blank=True)),
                ('poster', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('imdb_rating', models.FloatField(blank=True)),
                ('imdb_votes', models.IntegerField(blank=True)),
                ('box_office', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_body', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Movie')),
            ],
        ),
    ]
