# Generated by Django 2.2.3 on 2019-07-17 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190716_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='type',
            new_name='item_type',
        ),
    ]
