# Generated by Django 2.2.3 on 2019-07-17 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190717_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text_body',
            new_name='comment_body',
        ),
    ]
