# Generated by Django 2.2.3 on 2019-07-18 07:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190718_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='addded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
