# Generated by Django 2.2.3 on 2019-07-18 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_comment_addded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='addded',
            new_name='added',
        ),
    ]
